# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mark Chilenski
description: > # this means to ignore newlines until "baseurl:"
  Personal webpage of Mark Chilenski: MIT PhD student, plasma physicist and data analysis tool-builder.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://markchil.github.io" # the base hostname & protocol for your site
github_username:  markchil
linkedin_username: markchil

# Build settings
markdown: kramdown

# Added:
highlighter: rouge
email: markchil